//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 220.153368 on Stable branch
// Generated with ALiVE version 2.1.9.2501091
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O__BT_WordBearers_40k {
        displayName = "[BT] Custom Comp Word Bearers";
        side = 0;
        flag = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        priority = 0;
    };
};
class CfgEditorSubcategories
{
    class BT_WordBearers_MkII_Neophyte  {
        displayName = "Mk.2 Uninitiated"; // Name visible in the list
    };
    class BT_WordBearers_MkIII_Neophyte  {
        displayName = "Mk.3 Uninitiated"; // Name visible in the list
    };
    class BT_WordBearers_MkIV_Neophyte   {
        displayName = "Mk.4 Uninitiated"; // Name visible in the list
    };
    class BT_WordBearers_MkV_Neophyte   {
        displayName = "Mk.5 Uninitiated"; // Name visible in the list
    };
    class BT_WordBearers_MkVI_Neophyte   {
        displayName = "Mk.6 Uninitiated"; // Name visible in the list
    };
    class BT_WordBearers_MkII_Initiate_1    {
        displayName = "Mk.2 Initiate 1"; // Name visible in the list
    };
    class BT_WordBearers_MkIII_Initiate_1    {
        displayName = "Mk.3 Initiate 1"; // Name visible in the list
    };
    class BT_WordBearers_MkIV_Initiate_1     {
        displayName = "Mk.4 Initiate 1"; // Name visible in the list
    };
    class BT_WordBearers_MkV_Initiate_1     {
        displayName = "Mk.5 Initiate 1"; // Name visible in the list
    };
    class BT_WordBearers_MkVI_Initiate_1     {
        displayName = "Mk.6 Initiate 1"; // Name visible in the list
    };
    class BT_WordBearers_MkII_Initiate_2    {
        displayName = "Mk.2 Initiate 2"; // Name visible in the list
    };
    class BT_WordBearers_MkIII_Initiate_2    {
        displayName = "Mk.3 Initiate 2"; // Name visible in the list
    };
    class BT_WordBearers_MkIV_Initiate_2     {
        displayName = "Mk.4 Initiate 2"; // Name visible in the list
    };
    class BT_WordBearers_MkV_Initiate_2     {
        displayName = "Mk.5 Initiate 2"; // Name visible in the list
    };
    class BT_WordBearers_MkVI_Initiate_2     {
        displayName = "Mk.6 Initiate 2"; // Name visible in the list
    };
    class BT_WordBearers_MkII_Initiate_3    {
        displayName = "Mk.2 Initiate 3"; // Name visible in the list
    };
    class BT_WordBearers_MkIII_Initiate_3    {
        displayName = "Mk.3 Initiate 3"; // Name visible in the list
    };
    class BT_WordBearers_MkIV_Initiate_3     {
        displayName = "Mk.4 Initiate 3"; // Name visible in the list
    };
    class BT_WordBearers_MkV_Initiate_3     {
        displayName = "Mk.5 Initiate 3"; // Name visible in the list
    };
    class BT_WordBearers_MkVI_Initiate_3     {
        displayName = "Mk.6 Initiate 3"; // Name visible in the list
    };
    class BT_WordBearers_MkII_Veteran    {
        displayName = "Mk.2 Veteran"; // Name visible in the list
    };
    class BT_WordBearers_MkIII_Veteran    {
        displayName = "Mk.3 Veteran"; // Name visible in the list
    };
    class BT_WordBearers_MkIV_Veteran     {
        displayName = "Mk.4 Veteran"; // Name visible in the list
    };
    class BT_WordBearers_MkV_Veteran     {
        displayName = "Mk.5 Veteran"; // Name visible in the list
    };
    class BT_WordBearers_MkVI_Veteran     {
        displayName = "Mk.6 Veteran"; // Name visible in the list
    };
    class BT_WordBearers_MkII_Officer    {
        displayName = "Mk.2 Officer"; // Name visible in the list
    };
    class BT_WordBearers_MkIII_Officer    {
        displayName = "Mk.3 Officer"; // Name visible in the list
    };
    class BT_WordBearers_MkIV_Officer     {
        displayName = "Mk.4 Officer"; // Name visible in the list
    };
    class BT_WordBearers_MkV_Officer     {
        displayName = "Mk.5 Officer"; // Name visible in the list
    };
    class BT_WordBearers_MkVI_Officer     {
        displayName = "Mk.6 Officer"; // Name visible in the list
    };

};

class CfgGroups {
    class EAST {

        class O__BT_WordBearers_40k {
            name = "[BT] Custom Comp Word Bearers";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class TIOW_Tactical_WB_7;
    class TIOW_Tactical_WB_7_OCimport_01 : TIOW_Tactical_WB_7 { scope = 0; class EventHandlers; };
    class TIOW_Tactical_WB_7_OCimport_02 : TIOW_Tactical_WB_7_OCimport_01 { class EventHandlers; };
    #include ".\Mk2\Initiate1.hpp"
    #include ".\Mk2\Initiate2.hpp"
    #include ".\Mk2\Initiate3.hpp"
    #include ".\Mk2\Veteran.hpp"
    #include ".\Mk2\Officer.hpp"
    #include ".\Mk2\Neophyte.hpp"

    #include ".\Mk3\Initiate1.hpp"
    // #include ".\Mk3\Initiate2.hpp"
    // #include ".\Mk3\Initiate3.hpp"
    // #include ".\Mk3\Veteran.hpp"
    // #include ".\Mk3\Officer.hpp"
    // #include ".\Mk3\Neophyte.hpp"

    // #include ".\Mk4\Initiate1.hpp"
    // #include ".\Mk4\Initiate2.hpp"
    // #include ".\Mk4\Initiate3.hpp"
    // #include ".\Mk4\Veteran.hpp"
    // #include ".\Mk4\Officer.hpp"
    // #include ".\Mk4\Neophyte.hpp"

    // #include ".\Mk5\Initiate1.hpp"
    // #include ".\Mk5\Initiate2.hpp"
    // #include ".\Mk5\Initiate3.hpp"
    // #include ".\Mk5\Veteran.hpp"
    // #include ".\Mk5\Officer.hpp"
    // #include ".\Mk5\Neophyte.hpp"

    // #include ".\Mk6\Initiate1.hpp"
    // #include ".\Mk6\Initiate2.hpp"
    // #include ".\Mk6\Initiate3.hpp"
    // #include ".\Mk6\Veteran.hpp"
    // #include ".\Mk6\Officer.hpp"
    // #include ".\Mk6\Neophyte.hpp"

};